version: '3'
services:
  web:
    #image: sample:web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    environment:
      - REACT_APP_QUOTASERVER=<https://yourDomainName>:8080
    ports:
    - "8080:8080"
    volumes:
    - logvolume01:/var/log
    links:
      - db
  db:
    #build: 
    #  context: .
    #  dockerfile: /docker/db/Dockerfile
    #image: sample:db
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hosen
    volumes:
    - ./docker/db/backup.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
    - "5432:5432"

volumes:
  logvolume01: {}
